import { ModelSummary, ModelDetail } from './types';

const dummyImage = (seed: string, width = 320, height = 320) =>
  `https://picsum.photos/seed/${seed}/${width}/${height}`;

export const mockModels: ModelSummary[] = [
  {
    id: 'coding-mistral-7b-q4',
    name: 'Coding Mistral 7B Q4',
    creator: 'alice',
    family: 'Mistral',
    task: 'Code Generation',
    format: 'GGUF',
    sizeBytes: 4.1 * 1024 * 1024 * 1024,
    quantization: 'Q4_K_M',
    runtime: ['Ollama', 'llama.cpp', 'LM Studio'],
    license: 'Apache-2.0',
    seeders: 238,
    peers: 74,
    rating: 4.8,
    downloads: 982,
    trustLevel: 'verified_creator',
    compatibility: 'excellent',
    tags: ['coding', 'instruct', 'mistral', '7b', 'q4'],
    imageUrl: dummyImage('mistral-cover'),
    creatorAvatarUrl: dummyImage('alice-avatar', 96, 96),
  },
  {
    id: 'deepseek-coder-6-7b',
    name: 'DeepSeek Coder 6.7B',
    creator: 'deepseek-ai',
    family: 'DeepSeek',
    task: 'Code Generation',
    format: 'GGUF',
    sizeBytes: 3.8 * 1024 * 1024 * 1024,
    quantization: 'Q5',
    runtime: ['Ollama', 'llama.cpp'],
    license: 'DeepSeek License',
    seeders: 163,
    peers: 46,
    rating: 4.7,
    downloads: 750,
    trustLevel: 'hash_verified',
    compatibility: 'good',
    tags: ['coding', 'deepseek', '6.7b'],
    imageUrl: dummyImage('deepseek-cover'),
    creatorAvatarUrl: dummyImage('deepseek-avatar', 96, 96),
  },
  {
    id: 'qwen2-7b-instruct-q5',
    name: 'Qwen2 7B Instruct Q5',
    creator: 'qwen',
    family: 'Qwen',
    task: 'Text Generation',
    format: 'GGUF',
    sizeBytes: 4.6 * 1024 * 1024 * 1024,
    quantization: 'Q5',
    runtime: ['Ollama', 'llama.cpp'],
    license: 'Tongyi Qianwen License',
    seeders: 201,
    peers: 58,
    rating: 4.6,
    downloads: 639,
    trustLevel: 'verified_creator',
    compatibility: 'good',
    tags: ['instruct', 'qwen', '7b'],
    imageUrl: dummyImage('qwen-cover'),
    creatorAvatarUrl: dummyImage('qwen-avatar', 96, 96),
  },
  {
    id: 'gemma-2b-q4',
    name: 'Gemma 2B Q4',
    creator: 'google',
    family: 'Gemma',
    task: 'Text Generation',
    format: 'GGUF',
    sizeBytes: 1.6 * 1024 * 1024 * 1024,
    quantization: 'Q4',
    runtime: ['Ollama', 'Transformers'],
    license: 'Gemma License',
    seeders: 89,
    peers: 31,
    rating: 4.5,
    downloads: 544,
    trustLevel: 'signed',
    compatibility: 'excellent',
    tags: ['gemma', 'small', 'q4'],
    imageUrl: dummyImage('gemma-cover'),
    creatorAvatarUrl: dummyImage('google-avatar', 96, 96),
  },
];

export function getDetail(modelId: string): ModelDetail | undefined {
  const base = mockModels.find((m) => m.id === modelId);
  if (!base) return undefined;
  return {
    ...base,
    description:
      'Fine-tuned for coding assistants and autonomous agents. Strong performance in multi-file reasoning, refactoring and tool use. Trained on curated code and web corpora.',
    version: '1.0.0',
    publishedAt: '2024-05-07',
    files: [
      { path: 'model.gguf', sizeBytes: base.sizeBytes, hash: 'b3a7f1c9e8d2', chunkCount: 512, verified: true },
      { path: 'tokenizer.json', sizeBytes: 2.2 * 1024 * 1024, hash: 'd7c3a4b1f8a2', chunkCount: 14, verified: true },
    ],
    requirements: {
      minRamGb: 8,
      recommendedRamGb: 16,
      minVramGb: 6,
      gpuOptional: true,
    },
    manifestHash: 'deadbeef',
  };
}
